info:
  contact: {}
paths:
  /problem-list:
    get:
      description: 获取问题列表
      parameters:
      - description: page
        in: query
        name: page
        type: integer
      - description: size
        in: query
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: code":"200","msg":"","data":""}
          schema:
            type: string
      summary: 问题列表
      tags:
      - 公共方法
swagger: "2.0"
