info:
  contact: {}
paths:
  /login:
    post:
      description: 用户登录
      parameters:
      - description: username
        in: formData
        name: username
        type: string
      - description: password
        in: formData
        name: password
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: code":"200","msg":""}
          schema:
            type: string
      summary: 用户登录
      tags:
      - 公共方法
  /problem-detail:
    get:
      description: 问题详情
      parameters:
      - description: problem_identity
        in: query
        name: identity
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: code":"200","msg":"","data":""}
          schema:
            type: string
      summary: 问题详情
      tags:
      - 公共方法
  /problem-list:
    get:
      description: 获取问题列表
      parameters:
      - description: page
        in: query
        name: page
        type: integer
      - description: size
        in: query
        name: size
        type: integer
      - description: keyword
        in: query
        name: keyword
        type: string
      - description: category_identity
        in: query
        name: category_identity
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: code":"200","msg":"","data":""}
          schema:
            type: string
      summary: 问题列表
      tags:
      - 公共方法
  /send-code:
    post:
      description: 发送验证码
      parameters:
      - description: user_smail
        in: formData
        name: mail
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: code":"200","msg":""}
          schema:
            type: string
      summary: 发送验证码
      tags:
      - 公共方法
  /submit-list:
    get:
      description: 提交列表
      parameters:
      - description: page
        in: query
        name: page
        type: integer
      - description: size
        in: query
        name: size
        type: integer
      - description: problem_identity
        in: query
        name: problem_identity
        type: string
      - description: user_identity
        in: query
        name: user_identity
        type: string
      - description: status
        in: query
        name: status
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: code":"200","msg":"","data":""}
          schema:
            type: string
      summary: 提交列表
      tags:
      - 公共方法
  /user-detail:
    get:
      description: 用户详情
      parameters:
      - description: user_identity
        in: query
        name: identity
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: code":"200","msg":"","data":""}
          schema:
            type: string
      summary: 用户详情
      tags:
      - 公共方法
swagger: "2.0"
