info:
  contact: {}
paths:
  /admin/category-create:
    post:
      description: 创建分类
      parameters:
      - description: token
        in: header
        name: authorization
        required: true
        type: string
      - description: name
        in: formData
        name: name
        required: true
        type: string
      - description: parentId
        in: formData
        name: parentId
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: code":"200","msg":""}
          schema:
            type: string
      summary: 创建分类
      tags:
      - 管理员私有方法
  /admin/category-delete:
    delete:
      description: 删除分类
      parameters:
      - description: token
        in: header
        name: authorization
        required: true
        type: string
      - description: identity
        in: query
        name: identity
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: code":"200","msg":""}
          schema:
            type: string
      summary: 删除分类
      tags:
      - 管理员私有方法
  /admin/category-list:
    get:
      description: 获取分类列表
      parameters:
      - description: token
        in: header
        name: authorization
        required: true
        type: string
      - description: page
        in: query
        name: page
        type: integer
      - description: size
        in: query
        name: size
        type: integer
      - description: keyword
        in: query
        name: keyword
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: code":"200","msg":"","data":""}
          schema:
            type: string
      summary: 分类列表
      tags:
      - 管理员私有方法
  /admin/category-update:
    put:
      description: 修改分类
      parameters:
      - description: token
        in: header
        name: authorization
        required: true
        type: string
      - description: identity
        in: formData
        name: identity
        required: true
        type: string
      - description: name
        in: formData
        name: name
        required: true
        type: string
      - description: parentId
        in: formData
        name: parentId
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: code":"200","msg":""}
          schema:
            type: string
      summary: 修改分类
      tags:
      - 管理员私有方法
  /admin/problem-create:
    post:
      description: 创建问题
      parameters:
      - description: token
        in: header
        name: authorization
        required: true
        type: string
      - description: title
        in: formData
        name: title
        required: true
        type: string
      - description: content
        in: formData
        name: content
        required: true
        type: string
      - description: max_runtime
        in: formData
        name: max_runtime
        type: integer
      - description: max_mem
        in: formData
        name: max_mem
        type: integer
      - collectionFormat: csv
        description: category_ids
        in: formData
        items:
          type: string
        name: category_ids
        type: array
      - collectionFormat: csv
        description: test_cases
        in: formData
        items:
          type: string
        name: test_cases
        required: true
        type: array
      produces:
      - application/json
      responses:
        "200":
          description: code":"200","msg":""}
          schema:
            type: string
      summary: 创建问题
      tags:
      - 管理员私有方法
  /admin/problem-update:
    put:
      description: 修改问题
      parameters:
      - description: token
        in: header
        name: authorization
        required: true
        type: string
      - description: identity
        in: formData
        name: identity
        required: true
        type: string
      - description: title
        in: formData
        name: title
        required: true
        type: string
      - description: content
        in: formData
        name: content
        required: true
        type: string
      - description: max_runtime
        in: formData
        name: max_runtime
        type: integer
      - description: max_mem
        in: formData
        name: max_mem
        type: integer
      - collectionFormat: multi
        description: category_ids
        in: formData
        items:
          type: string
        name: category_ids
        type: array
      - collectionFormat: multi
        description: test_cases
        in: formData
        items:
          type: string
        name: test_cases
        required: true
        type: array
      produces:
      - application/json
      responses:
        "200":
          description: code":"200","msg":""}
          schema:
            type: string
      summary: 修改问题
      tags:
      - 管理员私有方法
  /login:
    post:
      description: 用户登录
      parameters:
      - description: username
        in: formData
        name: username
        type: string
      - description: password
        in: formData
        name: password
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: code":"200","msg":""}
          schema:
            type: string
      summary: 用户登录
      tags:
      - 公共方法
  /problem-detail:
    get:
      description: 问题详情
      parameters:
      - description: problem_identity
        in: query
        name: identity
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: code":"200","msg":"","data":""}
          schema:
            type: string
      summary: 问题详情
      tags:
      - 公共方法
  /problem-list:
    get:
      description: 获取问题列表
      parameters:
      - description: page
        in: query
        name: page
        type: integer
      - description: size
        in: query
        name: size
        type: integer
      - description: keyword
        in: query
        name: keyword
        type: string
      - description: category_identity
        in: query
        name: category_identity
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: code":"200","msg":"","data":""}
          schema:
            type: string
      summary: 问题列表
      tags:
      - 公共方法
  /rank-list:
    get:
      description: 用户排行榜
      parameters:
      - description: page
        in: query
        name: page
        type: integer
      - description: size
        in: query
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: code":"200","msg":"","data":""}
          schema:
            type: string
      summary: 用户排行榜
      tags:
      - 公共方法
  /register:
    post:
      description: 用户注册
      parameters:
      - description: user_name
        in: formData
        name: name
        required: true
        type: string
      - description: user_code
        in: formData
        name: userCode
        required: true
        type: string
      - description: user_password
        in: formData
        name: password
        required: true
        type: string
      - description: user_phone
        in: formData
        name: phone
        type: string
      - description: user_mail
        in: formData
        name: mail
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: code":"200","msg":""}
          schema:
            type: string
      summary: 用户注册
      tags:
      - 公共方法
  /send-code:
    post:
      description: 发送验证码
      parameters:
      - description: user_mail
        in: formData
        name: mail
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: code":"200","msg":""}
          schema:
            type: string
      summary: 发送验证码
      tags:
      - 公共方法
  /submit-list:
    get:
      description: 提交列表
      parameters:
      - description: page
        in: query
        name: page
        type: integer
      - description: size
        in: query
        name: size
        type: integer
      - description: problem_identity
        in: query
        name: problem_identity
        type: string
      - description: user_identity
        in: query
        name: user_identity
        type: string
      - description: status
        in: query
        name: status
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: code":"200","msg":"","data":""}
          schema:
            type: string
      summary: 提交列表
      tags:
      - 公共方法
  /user-detail:
    get:
      description: 用户详情
      parameters:
      - description: user_identity
        in: query
        name: identity
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: code":"200","msg":"","data":""}
          schema:
            type: string
      summary: 用户详情
      tags:
      - 公共方法
swagger: "2.0"
